name: Soundal
description: Open music encyclopedia that collects music metadata and makes it available to the public.
full_description: 'The ultimate source of music information by allowing anyone to contribute and releasing the data under open licenses<br>
<br>With a lot of features:
<br>- Search artists, albums, playlists and songs
<br>- Import your spotify playlists
<br>- Create local playlists
<br>- View top charts in every country'
#android: https://telegra.ph/Replace-this-link-07-23
#iOS: https://telegra.ph/Replace-this-link-07-23
#web: https://telegra.ph/Replace-this-link-07-23
screenshots:
  - 1.png
  - 2.png
  - 3.png
  - 4.png
#producthunt: https://telegra.ph/Replace-this-link-07-23
#companies:
  #- url: https://telegra.ph/Replace-this-link-07-23
  #  image: androidpolice.png
  #- url: https://telegra.ph/Replace-this-link-07-23
  #  image: producthunt.png
